sudo: false

git:
  submodules: false

language: node_js

notifications:
  email:
  - 1264889788@qq.com

node_js:
  - "10"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=dist
    - TEST_TYPE=compile
    - TEST_TYPE=test

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = dist ]; then
      npm run dist && \
      LIB_DIR=dist npm run test -- -w 2
    elif [ "$TEST_TYPE" = compile ]; then
      npm run compile && \
      LIB_DIR=lib npm run test -- -w 2 && \
      LIB_DIR=es npm run test-- -w 2
    elif [ "$TEST_TYPE" = test ]; then
      npm run test -- -w 2 --coverage && \
      bash <(curl -s https://codecov.io/bash) -cF web
    fi
